---

image: "quay.io/luzifer/repo-runner-image"
checkout_dir: /go/src/github.com/Luzifer/worktime

commands:
  - make publish

environment:
  CGO_ENABLED: 0
  ARCHS: linux/386 linux/amd64 linux/arm darwin/amd64 darwin/386 windows/386 windows/amd64
